# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-17 08:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AxfUser',
            fields=[
                ('phone', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=500, null=True)),
                ('isDelete', models.BooleanField(default=False)),
                ('cartNum', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'axfusers',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='axf.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='axf.AxfUser')),
            ],
        ),
    ]
